index:
    path:   /
    defaults: { _controller: RottenwoodVacancyBundle:Default:index }

api_vacancy_list:
    path:   /api/vacancy/list
    defaults: { _controller: RottenwoodVacancyBundle:Api:getVacancies }
#    requirements: { _method: POST }

api_department_list:
    path:   /api/department/list
    defaults: { _controller: RottenwoodVacancyBundle:Api:getDepartments }

api_language_list:
    path:   /api/language/list
    defaults: { _controller: RottenwoodVacancyBundle:Api:getLanguages }
