parameters:
#    rottenwood_vacancy.example.class: Rottenwood\VacancyBundle\Example

services:
#    rottenwood_vacancy.example:
#        class: %rottenwood_vacancy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
