#parameters:
#    vacancy.api.controller.class: Rottenwood\VacancyBundle\Controller\ApiController
#
#services:
#    # API controller was made as a service to inject entity manager
#    vacancy.api.controller:
#        class: %vacancy.api.controller.class%
#        arguments: []
