<?php

namespace Rottenwood\VacancyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VacancyRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacancyRepository extends EntityRepository {

}
